/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'M55_HE.Debug+AE722F80F55D5LS' 
 * Target:  'Debug+AE722F80F55D5LS' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::CMSIS Driver:I2C@2.0.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:SAI@2.0.0 */
#define RTE_Drivers_SAI              /* Driver SAI */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@2.0.0 */
#define RTE_Drivers_DMA                   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:PDM@2.0.0 */
#define RTE_Drivers_PDM              /* Driver PDM */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:SDMMC@2.0.0 */
#define RTE_Drivers_SD              /* Driver SD */


#endif /* RTE_COMPONENTS_H */
